name: Submodule Update
description: Action for performing multiple submodule updates

inputs:
  submodules:
    description: |
      List of submodules to update along with a ref to update token
      Each submodule should be listed on a separate line in the format 'path/to/submodule:ref'
    required: true
  commit:
    description: Whether to committing the updated submodules
    required: false
    default: 'true'
  push:
    description: Whether to push the updated submodules
    required: false
    default: 'true'
  branch:
    description: Branch name to use when pushing the updated submodules
    required: false
    default: 'submodule-update'
  path:
    description: Path to the root of the repository
    required: false
    default: '.'

outputs:
  updated:
    description: Whether any submodules were updated, either 'true' or 'false'

runs:
  using: node16
  main: index.js
