name: Submodule Update
description: Action for performing multiple submodule updates

inputs:
  submodules:
    description: |
      List of submodules to update along with a ref to update token
      Each submodule should be listed on a separate line in the format 'path/to/submodule:ref'
    required: true
  no-commit:
    description: Whether to skip committing the updated submodules (anything other than '' will skip committing)
    required: false
    default: ''

outputs:
  updated:
    description: Whether any submodules were updated, either 'true' or 'false'

runs:
  using: node16
  main: index.js
